# ESG Performance and Stock Market Trends in the S&P 500
### By Aashna Dorwal

In [109]:
import pandas as pd

# ESG data
esg_df = pd.read_csv("sp500_esg_data.csv")
# S&P 500 companies data
companies_df = pd.read_csv("sp500_companies.csv")

print("ESG Data:")
display(esg_df.head())

print("Companies Data:")
display(companies_df.head())

ESG Data:

,Symbol,Full Name,GICS Sector,GICS Sub-Industry,environmentScore,socialScore,governanceScore,totalEsg,highestControversy,percentile,ratingYear,ratingMonth,marketCap,beta,overallRisk
0,A,Agilent Technologies,Health Care,Life Sciences Tools & Services,1.12,6.42,6.10,13.64,2.0,7.98,2023.0,9.0,39751831552,1.054,8
1,AAL,American Airlines Group,Industrials,Passenger Airlines,9.94,11.65,4.76,26.35,2.0,54.48,2023.0,9.0,7335383552,1.433,10
2,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals",0.46,7.39,9.37,17.22,3.0,17.82,2023.0,9.0,3296096681984,1.240,1
3,ABBV,AbbVie,Health Care,Biotechnology,2.38,17.19,10.36,29.93,3.0,68.62,2023.0,9.0,341698445312,0.619,6
4,ABT,Abbott Laboratories,Health Care,Health Care Equipment,2.27,14.24,8.33,24.83,3.0,48.27,2023.0,9.0,205534380032,0.722,7

Companies Data:

,Exchange,Symbol,Shortname,Longname,Sector,Industry,Currentprice,Marketcap,Ebitda,Revenuegrowth,City,State,Country,Fulltimeemployees,Longbusinesssummary,Weight
0,NMS,AAPL,Apple Inc.,Apple Inc.,Technology,Consumer Electronics,254.49,3846819807232,1.346610e+11,0.061,Cupertino,CA,United States,164000.0,"Apple Inc. designs, manufactures, and markets ...",0.069209
1,NMS,NVDA,NVIDIA Corporation,NVIDIA Corporation,Technology,Semiconductors,134.70,3298803056640,6.118400e+10,1.224,Santa Clara,CA,United States,29600.0,NVIDIA Corporation provides graphics and compu...,0.059350
2,NMS,MSFT,Microsoft Corporation,Microsoft Corporation,Technology,Software - Infrastructure,436.60,3246068596736,1.365520e+11,0.160,Redmond,WA,United States,228000.0,Microsoft Corporation develops and supports so...,0.058401
3,NMS,AMZN,"Amazon.com, Inc.","Amazon.com, Inc.",Consumer Cyclical,Internet Retail,224.92,2365033807872,1.115830e+11,0.110,Seattle,WA,United States,1551000.0,"Amazon.com, Inc. engages in the retail sale of...",0.042550
4,NMS,GOOGL,Alphabet Inc.,Alphabet Inc.,Communication Services,Internet Content & Information,191.41,2351625142272,1.234700e+11,0.151,Mountain View,CA,United States,181269.0,Alphabet Inc. offers various products and plat...,0.042309

In [110]:
esg_columns = {
    "Full Name": "Company Name",
    "Symbol": "Ticker Symbol",
    "GICS Sector": "Sector",
    "totalEsg": "Total ESG Score",
    "environmentScore": "Environmental Score",
    "socialScore": "Social Score",
    "governanceScore": "Governance Score",
    "highestControversy": "Highest Controversy",
    "overallRisk": "Overall Risk",
}
esg_df = esg_df[list(esg_columns.keys())].rename(columns=esg_columns)
esg_df

,Company Name,Ticker Symbol,Sector,Total ESG Score,Environmental Score,Social Score,Governance Score,Highest Controversy,Overall Risk
0,Agilent Technologies,A,Health Care,13.64,1.12,6.42,6.10,2.0,8
1,American Airlines Group,AAL,Industrials,26.35,9.94,11.65,4.76,2.0,10
2,Apple Inc.,AAPL,Information Technology,17.22,0.46,7.39,9.37,3.0,1
3,AbbVie,ABBV,Health Care,29.93,2.38,17.19,10.36,3.0,6
4,Abbott Laboratories,ABT,Health Care,24.83,2.27,14.24,8.33,3.0,7
...,...,...,...,...,...,...,...,...,...
421,ExxonMobil,XOM,Energy,41.60,23.11,10.01,8.48,3.0,7
422,Xylem Inc.,XYL,Industrials,18.13,4.27,8.66,5.19,1.0,3
423,Yum! Brands,YUM,Consumer Discretionary,20.10,4.53,11.45,4.12,2.0,2
424,Zimmer Biomet,ZBH,Health Care,26.02,3.60,14.52,7.89,2.0,2
425,Zoetis,ZTS,Health Care,18.77,3.24,6.81,8.72,2.0,3

In [111]:
company_columns = {
    "Symbol": "Ticker Symbol",
    "Fulltimeemployees": "Full-time Employees",
    "Marketcap": "Market Cap",
    "Revenuegrowth": "Revenue Growth"
}
companies_df = companies_df[list(company_columns.keys())].rename(columns=company_columns)
companies_df.head()

  Ticker Symbol  Full-time Employees     Market Cap  Revenue Growth
0          AAPL             164000.0  3846819807232           0.061
1          NVDA              29600.0  3298803056640           1.224
2          MSFT             228000.0  3246068596736           0.160
3          AMZN            1551000.0  2365033807872           0.110
4         GOOGL             181269.0  2351625142272           0.151

In [112]:
# Integrating ESG data with Companies data by Ticker Symbol
merged_df = esg_df.merge(companies_df, on="Ticker Symbol", how="inner")
merged_df

,Company Name,Ticker Symbol,Sector,Total ESG Score,Environmental Score,Social Score,Governance Score,Highest Controversy,Overall Risk,Full-time Employees,Market Cap,Revenue Growth
0,Agilent Technologies,A,Health Care,13.64,1.12,6.42,6.10,2.0,8,17400.0,38415384576,-0.056
1,Apple Inc.,AAPL,Information Technology,17.22,0.46,7.39,9.37,3.0,1,164000.0,3846819807232,0.061
2,AbbVie,ABBV,Health Care,29.93,2.38,17.19,10.36,3.0,6,50000.0,310274424832,0.038
3,Abbott Laboratories,ABT,Health Care,24.83,2.27,14.24,8.33,3.0,7,114000.0,198127370240,0.049
4,Arch Capital Group,ACGL,Financials,22.46,1.47,10.10,10.89,2.0,5,6400.0,34234257408,0.418
...,...,...,...,...,...,...,...,...,...,...,...,...
417,ExxonMobil,XOM,Energy,41.60,23.11,10.01,8.48,3.0,7,62000.0,465308188672,-0.015
418,Xylem Inc.,XYL,Industrials,18.13,4.27,8.66,5.19,1.0,3,23000.0,28458575872,0.013
419,Yum! Brands,YUM,Consumer Discretionary,20.10,4.53,11.45,4.12,2.0,2,35000.0,36937969664,0.069
420,Zimmer Biomet,ZBH,Health Care,26.02,3.60,14.52,7.89,2.0,2,18000.0,21324808192,0.040
421,Zoetis,ZTS,Health Care,18.77,3.24,6.81,8.72,2.0,3,14100.0,74370031616,0.110

In [113]:
missing_values = merged_df.isna().sum()
missing_values

Company Name           0
Ticker Symbol          0
Sector                 0
Total ESG Score        0
Environmental Score    0
Social Score           0
Governance Score       0
Highest Controversy    0
Overall Risk           0
Full-time Employees    6
Market Cap             0
Revenue Growth         3
dtype: int64

In [114]:
merged_df.dropna(inplace=True)
merged_df

,Company Name,Ticker Symbol,Sector,Total ESG Score,Environmental Score,Social Score,Governance Score,Highest Controversy,Overall Risk,Full-time Employees,Market Cap,Revenue Growth
0,Agilent Technologies,A,Health Care,13.64,1.12,6.42,6.10,2.0,8,17400.0,38415384576,-0.056
1,Apple Inc.,AAPL,Information Technology,17.22,0.46,7.39,9.37,3.0,1,164000.0,3846819807232,0.061
2,AbbVie,ABBV,Health Care,29.93,2.38,17.19,10.36,3.0,6,50000.0,310274424832,0.038
3,Abbott Laboratories,ABT,Health Care,24.83,2.27,14.24,8.33,3.0,7,114000.0,198127370240,0.049
4,Arch Capital Group,ACGL,Financials,22.46,1.47,10.10,10.89,2.0,5,6400.0,34234257408,0.418
...,...,...,...,...,...,...,...,...,...,...,...,...
417,ExxonMobil,XOM,Energy,41.60,23.11,10.01,8.48,3.0,7,62000.0,465308188672,-0.015
418,Xylem Inc.,XYL,Industrials,18.13,4.27,8.66,5.19,1.0,3,23000.0,28458575872,0.013
419,Yum! Brands,YUM,Consumer Discretionary,20.10,4.53,11.45,4.12,2.0,2,35000.0,36937969664,0.069
420,Zimmer Biomet,ZBH,Health Care,26.02,3.60,14.52,7.89,2.0,2,18000.0,21324808192,0.040
421,Zoetis,ZTS,Health Care,18.77,3.24,6.81,8.72,2.0,3,14100.0,74370031616,0.110

In [115]:
merged_df.to_csv("sp500_bothmerged.csv", index=False)
merged_df

,Company Name,Ticker Symbol,Sector,Total ESG Score,Environmental Score,Social Score,Governance Score,Highest Controversy,Overall Risk,Full-time Employees,Market Cap,Revenue Growth
0,Agilent Technologies,A,Health Care,13.64,1.12,6.42,6.10,2.0,8,17400.0,38415384576,-0.056
1,Apple Inc.,AAPL,Information Technology,17.22,0.46,7.39,9.37,3.0,1,164000.0,3846819807232,0.061
2,AbbVie,ABBV,Health Care,29.93,2.38,17.19,10.36,3.0,6,50000.0,310274424832,0.038
3,Abbott Laboratories,ABT,Health Care,24.83,2.27,14.24,8.33,3.0,7,114000.0,198127370240,0.049
4,Arch Capital Group,ACGL,Financials,22.46,1.47,10.10,10.89,2.0,5,6400.0,34234257408,0.418
...,...,...,...,...,...,...,...,...,...,...,...,...
417,ExxonMobil,XOM,Energy,41.60,23.11,10.01,8.48,3.0,7,62000.0,465308188672,-0.015
418,Xylem Inc.,XYL,Industrials,18.13,4.27,8.66,5.19,1.0,3,23000.0,28458575872,0.013
419,Yum! Brands,YUM,Consumer Discretionary,20.10,4.53,11.45,4.12,2.0,2,35000.0,36937969664,0.069
420,Zimmer Biomet,ZBH,Health Care,26.02,3.60,14.52,7.89,2.0,2,18000.0,21324808192,0.040
421,Zoetis,ZTS,Health Care,18.77,3.24,6.81,8.72,2.0,3,14100.0,74370031616,0.110

In [116]:
# Merging web scraped SlickCharts df to Merged df
slickcharts_df = pd.read_csv("sp500_slickcharts.csv")
slickcharts_df

     Rank                      Company Symbol YTD Return
0       1              CVS HEALTH CORP    CVS     51.44%
1       2  PHILIP MORRIS INTERNATIONAL     PM     31.36%
2       3                 NEWMONT CORP    NEM     29.74%
3       4                     AT+T INC      T     25.08%
4       5                  CENCORA INC    COR     23.47%
..    ...                          ...    ...        ...
498   499                    TESLA INC   TSLA    -33.52%
499   500                 TERADYNE INC    TER    -34.39%
500   501                  MODERNA INC   MRNA    -34.68%
501   502             ON SEMICONDUCTOR     ON    -36.24%
502   503         DECKERS OUTDOOR CORP   DECK    -44.19%

[503 rows x 4 columns]

In [117]:
slickcharts_df.rename(columns={"Symbol": "Ticker Symbol"}, inplace=True)

final_df = merged_df.merge(slickcharts_df[["Ticker Symbol", "YTD Return"]], on="Ticker Symbol", how="inner")
final_df

,Company Name,Ticker Symbol,Sector,Total ESG Score,Environmental Score,Social Score,Governance Score,Highest Controversy,Overall Risk,Full-time Employees,Market Cap,Revenue Growth,YTD Return
0,Agilent Technologies,A,Health Care,13.64,1.12,6.42,6.10,2.0,8,17400.0,38415384576,-0.056,-15.10%
1,Apple Inc.,AAPL,Information Technology,17.22,0.46,7.39,9.37,3.0,1,164000.0,3846819807232,0.061,-10.87%
2,AbbVie,ABBV,Health Care,29.93,2.38,17.19,10.36,3.0,6,50000.0,310274424832,0.038,16.08%
3,Abbott Laboratories,ABT,Health Care,24.83,2.27,14.24,8.33,3.0,7,114000.0,198127370240,0.049,16.43%
4,Arch Capital Group,ACGL,Financials,22.46,1.47,10.10,10.89,2.0,5,6400.0,34234257408,0.418,4.10%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,ExxonMobil,XOM,Energy,41.60,23.11,10.01,8.48,3.0,7,62000.0,465308188672,-0.015,10.66%
404,Xylem Inc.,XYL,Industrials,18.13,4.27,8.66,5.19,1.0,3,23000.0,28458575872,0.013,3.33%
405,Yum! Brands,YUM,Consumer Discretionary,20.10,4.53,11.45,4.12,2.0,2,35000.0,36937969664,0.069,18.46%
406,Zimmer Biomet,ZBH,Health Care,26.02,3.60,14.52,7.89,2.0,2,18000.0,21324808192,0.040,6.38%
407,Zoetis,ZTS,Health Care,18.77,3.24,6.81,8.72,2.0,3,14100.0,74370031616,0.110,-0.63%

In [118]:
final_df.to_csv("final_merged_sp500.csv", index=False)